pull_request_rules:
  - name: CI passes and is dev-dependency package from dependabot
    conditions:
      - check-success=Test (ubuntu-latest)
      - check-success=Test (windows-latest)
      - check-success=Test (macos-latest)
      - check-success=Prettier
      - check-success=Typecheck
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=^chore\(deps-dev\).*$
      - base=main
    actions:
      merge:
        method: merge
